---
sudo: required

language: c

services:
  - docker

before_install:
  - docker build -t atgreen/s2i-el-cloud-image:$TRAVIS_BUILD_NUMBER .

script:
  -

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push atgreen/s2i-el-cloud-image:$TRAVIS_BUILD_NUMBER;
    fi
