---
sudo: required

language: c

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

before_install:
  - docker build -t atgreen/s2i-el-cloud-image:$COMMIT .

script:
  -

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker tag atgreen/s2i-el-cloud-image:$COMMIT atgreen/s2i-el-cloud-image:latest;
      docker tag atgreen/s2i-el-cloud-image:$COMMIT atgreen/s2i-el-cloud-image:travis-$TRAVIS_BUILD_NUMBER;
      docker push atgreen/s2i-el-cloud-image;
    fi
